### ISSUE TITLE
Cleaning up

### ISSUE THREAD

**Issue by nbrucy** [blaizot/ramses-tutorials#16]
Cleaning To-do list:

- [x] The git clone instruction are too precise

- [x] remove execution information from the notebooks (maybe keep the plots)

- [x] Should we remove the old .pdf, .rtf files?
  Eg. 
  
    - [x]  `Forced-Turbulence/tutorial_forced_turbulence.rtf`
    - [x]  `Fundamentals/RAMSES_tutorial-3.pdf`
    - [x] `Fundamentals/main.tex`

Edit: transformed this into a to-do list, was initially only about the old pdf/rtf files.

**Comment by jokirosdahl** [comment]
I think so ... let's maybe get the green light from @bcommerc  first.
