### ISSUE TITLE
Issue in the fundamentals tutorial

### ISSUE THREAD

**Issue by nbrucy** [blaizot/ramses-tutorials#17]
In Section 5.1, the folder `ramses-tutorials/Fundamentals/stromgren` does not exists.
One can use the strogrem test in ramses but then the compile line is wrong (`NGROUPS` has to be 3 and not 1, and `NMETAL` should be 1.).

**Comment by jokirosdahl** [comment]
Aargh sorry. Just added the stromgren directory, with the namelist, and pushed.
Thanks for taking a look!
